### ISSUE TITLE
checkhealth complains about capitalcase

### ISSUE THREAD

**Issue by teto** [nvim-neorocks/rocks-git.nvim#40]
was running `checkhealth rocks` for something unrelated and was surprised to see 
```
Checking rocks.toml ~
- ERROR Plugin name is not lowercase: Solarized
- WARNING Skipping tree-sitter parsers check due to errors in rocks.toml
```

I could track it to
https://github.com/nvim-neorocks/rocks.nvim/issues/288

and this in my config:
```
[plugins.Solarized]
git = "vim-scripts/Solarized"
rev = "1.0.0b1^{}"
colorscheme= "solarized"
```
not sure what to. Seems like rocks-git somehow escapes the lowercasing process

**Comment by mrcjkb** [comment]
`luarocks install` only accepts lower case names.
That's why we have the health check. 

The rocks.nvim health check isn't aware of extensions like rocks-git.nvim.

In this case, if you give `git clone` with a lower case URL, it'll clone the repo into a directory with a lower case name.
I suppose the solution would be for rocks-git to lowercase both the name and URL.
