### ISSUE TITLE
random notes during my install of iron.nvim

### ISSUE THREAD

**Issue by teto** [nvim-neorocks/rocks-git.nvim#74]
Just a few remarks as I can't address this straightaway (with "rocks-git.nvim"= "2.4.2"):
1. When doing `Rocks install ALREADY_INSTALLED_PLUGIN`, rocks-git asks for `Delete and reinstall [y/n]` without telling the default but there seems to be one (no):
```
                }, function(yesno)
                    future.set(yesno and yesno:match("^y.*") ~= nil or false)
                end)
```
so maybe we should show `Delete and reinstall [y/N]`.

2. By default, rocks-git selects the latest tag and that's great. In my case it was 2 years old though so I tried to ask for the master branch with `Rocks install Vigemus/iron.nvim branch=master` which ends in:
```
[plugins."iron.nvim"]
git = "vigemus/iron.nvim"
rev = "v3.0"
branch = "master"
```
It's a bit confusing as I now dont know which one is used ("master" or "v3.0" ? EDIT: it's v3.0)

3. This last experience makes me wonder if we could/should warn when installing too old software. If the tag is 2 years old, maybe the user want to switch to the main branch ? it's possible main is also 2 years old (in my case iron.nvim case, master is 3 months old so it makes a difference), but over a threshold, maybe we could add a comment to make it easier to spot old versions
```
[plugins."iron.nvim"]
git = "vigemus/iron.nvim"
rev = "v3.0"   # released 2022-05-17
```

4. More a rocks feature but during a `:Rocks update` I get a `rocks-git -> 2.4.2 installed`, would be even better to have `rocks-git 2.2.0 -> 2.4.2 installed` but that probably introduces complexity and brittleness for little gain ?

**Comment by teto** [comment]
3) should maybe be a user hook instead

**Comment by mrcjkb** [comment]
2. is a bug - fixed in https://github.com/nvim-neorocks/rocks-git.nvim/pull/75

**Comment by mrcjkb** [comment]
1. addressed in https://github.com/nvim-neorocks/rocks-git.nvim/pull/77

**Comment by mrcjkb** [comment]
3. is a larger feature and would need a separate issue (with the `need-triage` label).
Someone else requested the same thing for rocks.nvim / luarocks packages, but that would require support for that to be implemented in rocks/luarocks.
Since we're focusing on migrating to rocks, I don't know if we want to add support for that to rocks-git.nvim. It might make more sense to add support for git packages without a rockspec to rocks itself (with proper lockfile support, etc.).

**Comment by mrcjkb** [comment]
Regarding 4: That message is shown when you run `:Rocks update {rock}`, because the command is just an alias for `:Rocks install {rock}`.
Sure, it would be nicer if it displayed the previously installed version, but that would also increase complexity because we would have to add logic for getting the previously installed version and checking if there exists a previously installed version.
I'm not sure if that's worth it.

**Comment by teto** [comment]
You fixed the most important work. Awesome. Closing then.
